chore: update changelog
deepin-community/opencv-mobile pull request #1
Opened 2023-08-30 07:44 UTC by pengfeixx

update changelog

Log: update changelog

2023-08-30 08:28 UTC, pengfeixx commented
/retest

2023-08-30 09:05 UTC, hudeng-go requested changes

2023-08-30 09:05 UTC, hudeng-go commented on debian/changelog
> +opencv-mobile (4.5.4) UNRELEASED; urgency=medium
上游版本是14吧，按说应该是+deepin这种？ 还有，unreleased应该改成unstable。

2023-08-30 09:35 UTC, pengfeixx commented on debian/changelog
> +opencv-mobile (4.5.4) UNRELEASED; urgency=medium
debian上游没有这个包，之前的14应该是随意定的

2023-08-30 09:51 UTC, wineee commented on debian/changelog
> +opencv-mobile (4.5.4) UNRELEASED; urgency=medium
4.5.4 < 14+u002

这个版本号语义比之前低，安装旧版的用户不会得到更新，更改版本号应该用 `1:4.5.4`

2023-08-30 10:09 UTC, pengfeixx commented on debian/changelog
> +opencv-mobile (4.5.4) UNRELEASED; urgency=medium
已修改

2023-08-30 10:19 UTC, wineee commented on debian/changelog
> +opencv-mobile (4.5.4) UNRELEASED; urgency=medium
> debian上游没有这个包，之前的14应该是随意定的

不是随意定的，是基于 https://github.com/nihui/opencv-mobile 的 v14 tag，上游是 opencv 的 patch， 这个仓库相比上游加了 opencv 的本体代码，我推荐用 `1:4.5.4-14` 这种

2023-08-31 01:44 UTC, pengfeixx commented on debian/changelog
> +opencv-mobile (4.5.4) UNRELEASED; urgency=medium
> > debian上游没有这个包，之前的14应该是随意定的
> 
> 不是随意定的，是基于 https://github.com/nihui/opencv-mobile 的 v14 tag，上游是 opencv 的 patch， 这个仓库相比上游加了 opencv 的本体代码，我推荐用 `1:4.5.4-14` 这种

tag号中不支持-，修改为1:4.5.4+14

2023-08-31 02:20 UTC, pengfeixx commented
@hudeng-go @wineee

2023-08-31 02:24 UTC, wineee approved these changes
LGTM

2023-08-31 02:33 UTC, hudeng-go commented
/approve

2023-08-31 02:34 UTC, merged